name: Olas
options:
  bundleIdPrefix: com.olas
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    # Code Signing Settings - Update these with your values
    DEVELOPMENT_TEAM: "456SHKPP26"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    PROVISIONING_PROFILE_SPECIFIER: ""
    
    # App Settings
    PRODUCT_BUNDLE_IDENTIFIER: com.olas.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "2"
packages:
  NDKSwift:
    path: ../NDKSwift
targets:
  Olas:
    type: application
    platform: iOS
    sources: 
      - Olas
    dependencies:
      - package: NDKSwift
        product: NDKSwift
      - package: NDKSwift
        product: NDKSwiftUI
    info:
      path: Olas/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: "Olas needs access to your camera to capture photos"
        NSPhotoLibraryUsageDescription: "Olas needs access to your photo library to select images"
        NSPhotoLibraryAddUsageDescription: "Olas needs permission to save photos to your library"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIRequiredDeviceCapabilities:
          - arm64
    settings:
      base:
        INFOPLIST_FILE: Olas/Info.plist
        PRODUCT_NAME: Olas
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        SWIFT_VERSION: 5.9